### ISSUE TITLE
[Bug Report] 移动端无侧边栏打开按钮

### ISSUE THREAD

**Issue by YunYouJun** [OhYee/blotter_page#4]
如图，移动端没有找到如桌面端的侧边栏展开按钮。

![022DC03F-A454-4321-B5ED-12936314CAB1](https://user-images.githubusercontent.com/25154432/89741482-45570f00-dac4-11ea-92f4-5fcdc55d33a1.png)

**Comment by OhYee** [comment]
@YunYouJun 能提供下屏幕大小和浏览器信息么，我没重现出来

**Comment by YunYouJun** [comment]
iPhone11。1792*828。Safari 与 Chrome 均无。


安卓平台下手机测试正常。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: OhYee <notifications@github.com&gt;
发送时间: 2020年8月10日 10:34
收件人: OhYee/blotter_page <blotter_page@noreply.github.com&gt;
抄送: 云游君 <me@yunyoujun.cn&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[OhYee/blotter_page] [Bug Report] 移动端无侧边栏打开按钮 (#4)





 
@YunYouJun 能提供下屏幕大小和浏览器信息么，我没重现出来

**Comment by OhYee** [comment]
@YunYouJun 重新部署了，Ant Design 的 Layout 多套了一层把定位搞乱了
